export const mockNotes = [
  {
    id: "work-1",
    content: "First Note",
    category: "Work",
    order: 1,
    marked: true,
  },
  {
    id: "work-2",
    content: "Two Three",
    category: "Work",
    order: 2,
    marked: false,
  },
  {
    id: "work-3",
    content: "Test stuff",
    category: "Work",
    order: 3,
    marked: false,
  },
  {
    id: "personal-1",
    content: "Personal Jesus",
    category: "Personal",
    order: 1,
    marked: false,
  },
  {
    id: "personal-2",
    content: "Yolo",
    category: "Personal",
    order: 2,
    marked: false,
  },
  {
    id: "personal-3",
    content: "Dunno what to say",
    category: "Personal",
    order: 3,
    marked: false,
  },
  {
    id: "ideas-1",
    content: "First Note",
    category: "Ideas",
    order: 1,
    marked: false,
  },
  {
    id: "ideas-2",
    content: "Second Note",
    category: "Ideas",
    order: 2,
    marked: true,
  },
  {
    id: "ideas-3",
    content: "Third Note",
    category: "Ideas",
    order: 3,
    marked: true,
  },
  {
    id: "ideas-4",
    content: "Fourth Note",
    category: "Ideas",
    order: 4,
    marked: false,
  },
  {
    id: "ideas-5",
    content: "Fifth Note",
    category: "Ideas",
    order: 5,
    marked: true,
  },
];
